version: '3.8'

services:
  virtuoso:
    image: openlink/virtuoso-opensource-7
    container_name: virtuoso
    ports:
      - "8890:8890"
      - "1111:1111"
    environment:
      DBA_PASSWORD: dba
    volumes:
      - ./rdf:/data
      - ./database:/opt/virtuoso-opensource/database
    restart: always